# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run Deno lint and test.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A --unstable --coverage=coverage
        
      - name: Generate code coverage report
        run: deno coverage ./coverage --unstable --lcov > coverage.lcov
      
      - name: Upload to codecov
        uses: codecov/codecov-action@v2.0.2
        with:
          token: a95aa1af-30cd-4494-b33b-4168373f9d16
          file: ./coverage.lcov
          
